# Generated by Django 2.1.4 on 2018-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('Acceptable', 'Acceptable'), ('Bad', 'Bad'), ('Good', 'Good')], default='Acceptable', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
    ]
