# Generated by Django 2.1.4 on 2019-01-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_auto_20190104_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercollection',
            old_name='user',
            new_name='owner',
        ),
    ]
