# Generated by Django 2.1.4 on 2019-01-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0026_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Book'),
        ),
    ]
