# Generated by Django 2.1.4 on 2019-01-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0028_auto_20190105_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='coreapp.Book'),
        ),
    ]
