# Generated by Django 2.1.4 on 2019-01-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0030_auto_20190105_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(null=True, to='coreapp.Book'),
        ),
    ]
