# Generated by Django 2.1.4 on 2019-01-05 21:16

import coreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0032_auto_20190105_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=coreapp.models.random_img, null=True, upload_to='book_images/'),
        ),
    ]
