# Generated by Django 2.1.4 on 2019-01-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0035_oldrequests_requests_shippingaddress_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='offerer_book',
            new_name='offerrer_book',
        ),
    ]
