# Generated by Django 2.1.4 on 2019-01-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0036_auto_20190111_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.Profile'),
        ),
    ]
