# Generated by Django 2.1.4 on 2019-01-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0037_shippingaddress_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippingaddress', to='coreapp.Profile'),
        ),
    ]
