# Generated by Django 2.1.4 on 2019-01-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0038_auto_20190111_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.Profile'),
        ),
    ]
