# Generated by Django 2.1.4 on 2019-01-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0042_auto_20190111_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='coreapp.Profile'),
        ),
    ]
