# Generated by Django 2.1.4 on 2019-01-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0043_auto_20190111_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(choices=[('421202', '421202'), ('421201', '421201'), ('421203', '421203')], max_length=100),
        ),
    ]
