# Generated by Django 2.1.4 on 2019-01-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0049_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_or_exchange',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Exchange', 'Exchange')], default='Exchange', max_length=100),
        ),
    ]
