# Generated by Django 2.1.4 on 2019-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0050_book_buy_or_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='buy_or_exchange',
        ),
        migrations.AddField(
            model_name='book',
            name='sell_or_exchange',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Exchange', 'Exchange')], default='Exchange', max_length=100),
        ),
    ]
