# Generated by Django 2.1.4 on 2019-01-17 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreapp', '0053_auto_20190116_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalBuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Book')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('selleraddres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selleraddress', to='coreapp.ShippingAddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('useraddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='coreapp.ShippingAddress')),
            ],
        ),
    ]
