# Generated by Django 2.1.4 on 2019-01-17 04:25

import coreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0054_finalbuyorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=coreapp.models.random_img, upload_to='profile_images/'),
        ),
    ]
