# Generated by Django 2.1.4 on 2019-01-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0055_auto_20190117_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalbuyorder',
            old_name='selleraddres',
            new_name='selleraddress',
        ),
        migrations.AddField(
            model_name='finalbuyorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
