# Generated by Django 2.1.4 on 2019-01-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0056_auto_20190117_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalbuyorder',
            old_name='Book',
            new_name='book',
        ),
    ]
