# Generated by Django 2.1.4 on 2019-01-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0057_auto_20190117_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbuyorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
