# Generated by Django 2.1.4 on 2019-01-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0058_auto_20190118_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbuyorder',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Book'),
        ),
        migrations.AlterField(
            model_name='finalbuyorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalbuyorder',
            name='selleraddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selleraddress', to='coreapp.ShippingAddress'),
        ),
        migrations.AlterField(
            model_name='finalbuyorder',
            name='useraddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='coreapp.ShippingAddress'),
        ),
    ]
