# Generated by Django 2.1.4 on 2019-01-18 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0059_auto_20190118_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbuyorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
