# Generated by Django 2.1.4 on 2019-01-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0063_auto_20190119_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sell_or_exchange',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Exchange', 'Exchange')], default='Exchange', help_text='By adding items to exchange you can make requests to ther users for exchange!', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(choices=[('421202', '421202'), ('421201', '421201'), ('421204', '421204'), ('421203', '421203'), ('421301', '421301')], default='421202', help_text='We only operate in these locations for now!', max_length=100),
        ),
    ]
