# Generated by Django 2.1.4 on 2019-01-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0064_auto_20190119_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(help_text='We only deal with original books with ISBN codes, pirated books will not be accepted.', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_or_exchange',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Exchange', 'Exchange')], default='Exchange', help_text='By adding items to exchange you can make requests to other users for exchange.', max_length=100),
        ),
    ]
