# Generated by Django 2.1.4 on 2019-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0065_auto_20190119_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalbuyorder',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
