# Generated by Django 2.1.4 on 2019-01-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0069_completedbuyorder_completedtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedbuyorder',
            name='book',
        ),
        migrations.RemoveField(
            model_name='completedbuyorder',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='completedbuyorder',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='completedbuyorder',
            name='selleraddress',
        ),
        migrations.RemoveField(
            model_name='completedbuyorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='completedbuyorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='completedbuyorder',
            name='useraddress',
        ),
        migrations.AddField(
            model_name='completedbuyorder',
            name='book_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
