# Generated by Django 2.1.4 on 2019-01-25 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreapp', '0070_auto_20190125_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedbuyorder',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='completedbuyorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedbuyorder',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedbuyorder',
            name='selleraddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_selleraddress', to='coreapp.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='completedbuyorder',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='completedbuyorder',
            name='useraddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_address', to='coreapp.ShippingAddress'),
        ),
    ]
