# Generated by Django 2.1.4 on 2019-01-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0072_completedbuyorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtransaction',
            name='offerrer_book',
        ),
        migrations.RemoveField(
            model_name='completedtransaction',
            name='requester_book',
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='offerrer_author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='offerrer_book_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='requester_author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='requester_book_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
