# Generated by Django 2.1.4 on 2019-01-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0075_auto_20190126_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name_plural': 'Requests'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
