# Generated by Django 2.1.4 on 2019-01-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0076_auto_20190129_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldrequests',
            options={'verbose_name_plural': 'Old Requests'},
        ),
    ]
