# Generated by Django 2.1.4 on 2019-01-29 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0077_auto_20190129_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('Almost New', 'Almost New'), ('Acceptable', 'Acceptable'), ('Good', 'Good'), ('Bad', 'Bad')], default='Acceptable', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(help_text='Enter your 10 digit phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')]),
        ),
    ]
