# Generated by Django 2.1.4 on 2019-01-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0078_auto_20190129_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_images/'),
        ),
    ]
